name: Build

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read Node version
        id: node_version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Set Node version
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.node_version.outputs.NVMRC }}'
      - name: Install dependencies
        run: npm i
      - name: Run Publish All
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish:all
